# Generated by Django 6.0.1 on 2026-01-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capital', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('subregion', models.CharField(max_length=200)),
                ('population', models.PositiveIntegerField()),
                ('area', models.FloatField()),
                ('currency', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('is_independent', models.BooleanField(default='True')),
            ],
        ),
    ]
